repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [check, src/, tests/]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
