repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [src/, tests/]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
  - repo: local
    hooks:
      - id: vulture
        name: vulture
        entry: vulture
        language: python
        additional_dependencies: [vulture>=2.14]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
